apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
  namespace: shop
data:
  GATEWAY_PORT: "5000"
  CHECKOUT_PORT: "5001"
  PRICING_PORT: "5002"
  INVENTORY_PORT: "5003"
  QUOTE_PORT: "5004"
  REQUEST_TIMEOUT_MS: "800"
  CURRENCY: "GBP"
  CHECKOUT_URL: "http://checkout-svc:5001"
  PRICING_URL: "http://pricing-svc:5002"
  INVENTORY_URL: "http://inventory-svc:5003"
  QUOTE_URL: "http://quote-svc:5004"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
