apiVersion: v1
kind: Secret
metadata:
  name: shop-db-secret
  namespace: shop
type: Opaque
stringData:
  DB_NAME: "checkoutdb"
  DB_USER: "checkoutuser"
  DB_PASSWORD: "checkoutpass"
  POSTGRES_DB: "checkoutdb"
  POSTGRES_USER: "checkoutuser"
  POSTGRES_PASSWORD: "checkoutpass"
